name: basebuild

on:
  push:
    tags:
      - v*

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ">=14.17.0"
          cache: "npm"
          cache-dependency-path: ./web_src/sitebuild/package-lock.json

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.21.1"

      - name: Build CSS
        working-directory: ./web_src/sitebuild
        run: |
          npm ci
          npm run build-copy

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
